nuvolaris/nuvolaris-operator

nuvolaris/redpanda/redpanda-pod.yaml, nuvolaris/redpanda/redpanda-svc.yaml
=> add redpanda [testing]

Dockerfile, Taskfile.yml, TaskfileTest.yml, deploy/mongodb-operator/mongodb-operator.yaml, deploy/mongodb/mongocli.yaml, deploy/mongodb/mongodb-auth-nuvolaris.yaml, deploy/mongodb/mongodb-auth.yaml, deploy/mongodb/mongodb-svc.yaml, deploy/mongodb/mongodb.yaml, deploy/nuvolaris-operator/whisk.yaml, deploy/nuvolaris-permissions/operator-clusterroles.yaml, deploy/nuvolaris-permissions/operator-roles.yaml, deploy/nuvolaris-permissions/standalone-roles.yaml, nuvolaris/actionexecutor.py, nuvolaris/kube.py, nuvolaris/kustomize.py, nuvolaris/main.py, nuvolaris/mongodb.py, nuvolaris/templates/mongodb-auth-nuvolaris.yaml, nuvolaris/templates/mongodb-auth.yaml, nuvolaris/templates/mongodb-config.yaml, tests/eks/whisk.yaml, tests/generic/whisk.yaml, tests/kind/mongodb_test.ipy, tests/kind/whisk.yaml, tests/microk8s/whisk.yaml, tests/mongo.js, tests/mongo.yaml, tests/whisk.yaml
- nuvolaris-operator support now deployment for mongoldb-community-operator 0.7.5
- fixed nuvolaris-operator permissions to allow deployment of the above operator
- added tests for mongodb operator support
=> #117 integration of mongodb-community-operator in nuvolaris-operator

nuvolaris/actionexecutor.py
Added support to internal scheduler to handle actions annotated with cron or autoexec key with values set to true.
autoexec are set with value to false after invocation to forbid further executions.
=> Implements nuvolaris/nuvolaris#120

clusters/eks-cluster.yml, clusters/eks.yml, nuvolaris/couchdb.py, nuvolaris/couchdb_util.py, nuvolaris/util.py, tests/kind/couchdb_test.ipy, tests/kind/dbinit.ipy
Fixed a problem with the couchdb-init job which was systematicallly failing at 1st execution. The python job was returning a boolean value set to True and this was interpreted as an exit code set to 1 setting the Job status to error. As part of the fix it has been introduced an addiitonal check that couchdb pod is ready before starting the db initialization process.
=> Fixes nuvolaris/nuvolaris#131

deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml, deploy/openwhisk-standalone/standalone-preload.yaml, nuvolaris/templates/mongodb-sts.yaml
Improvement/changes introduced
- Uses the runtimes.json taken from aruba-poc branch
- adds a job to preload some runtime images
- increase standalone mongodb liveness probe initial delay to prevent un-necessary restarts
=> Fixes nuvolaris/nuvolaris#139

nuvolaris/main.py, nuvolaris/openwhisk_patcher.py, nuvolaris/openwhisk_standalone.py, nuvolaris/util.py
Ensures that community operatore execute OpenWhisk controller using configured image using whisk.yaml parameters
- controller.image
- controller.tag
Defaults 
- controller.image=ghcr.io/nuvolaris/openwhisk-controller
- controller.tag=0.3.0-morpheus.22122609
=> [FIX] ensures controller is created using given image name and tag. 

Taskfile.yml, deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml
This PR introduce nodes:18 as default nodes runtime.
=> Provides nodes:18 as default runtime

.github/cisetup.sh, .github/workflows/image.yml, .gitignore, Taskfile.yml, TaskfileTest.yml, actions/login/__main__.py, deploy/nuvolaris-operator/operator-pod.yaml, nuvolaris/templates/couchdb-init.yaml, tests/kind/action_executor_test.ipy, tests/kind/couchdb_util_test.ipy, tests/kind/dbinit.ipy, tests/kind/wskadmin.ipy
nuv/login action is packaged as a python archive and main action file __main__.py was excluded because of .gitignore rules
=> [FIX] system action for login API was excluded by git ignore rules

deploy/nuvolaris-permissions/whisk-crd.yaml, deploy/nuvolaris-permissions/whisk-user-crd.yaml, tests/eks/whisk.yaml, tests/generic/whisk.yaml, tests/k3s/minimal.yaml, tests/k3s/whisk.yaml, tests/kind/whisk.yaml, tests/lks/whisk.yaml, tests/microk8s/whisk.yaml, tests/openshift/whisk.yaml, tests/whisk.yaml
This PR formalise the content of whisk-crd and whisk-user-crd and adds proper description on fields where needed.
=> Implements nuvolaris/nuvolaris#164

deploy/nuvolaris-permissions/whisk-crd.yaml
added missing attributes to whisk-crd.yaml
=> chore: added missing attributes to whisk-crd.yaml

.gitignore, nuvolaris/kustomize.py
This PR adds a new renderTemplate method to customise.py to simply generate a merged yaml file starting from a given template.
=> chore: added renderTemplate to kustomize.py

deploy/mongodb-standalone/mongodb-svc.yaml, nuvolaris/mongodb.py
mongodb standalone was not binding mongodb server anymore
=> fix: mongodb standalone was not binding mongodb server anymore

TaskfileTest.yml, deploy/openwhisk-standalone/standalone-sts.yaml, nuvolaris/templates/standalone-sts.yaml
This PR fixes the issue on __OW_API_HOST
now __OW_API_HOST it is properly set to something like controller.nuvolaris.svc.cluster.local
=> Fixes nuvolaris/nuvolaris#206

deploy/nuvolaris-permissions/whisk-crd.yaml, nuvolaris/minio.py, tests/kind/whisk.yaml
fix: saving minio_bucket_web and minio_bucket_data into cm/config
=> Fixes for nuvolaris/nuvolaris#208

Taskfile.yml, actions/Taskfile.yml, clusters/k3s.yml, nuvolaris/endpoint.py, nuvolaris/issuer.py, nuvolaris/patcher.py
This PR ensure that tis activation will deploy/update also the cluster issuer used to request let's encrypt certificate
=> fix: tls activation requires also a cluster issuer

TaskfileTest.yml, deploy/nuvolaris-permissions/whisk-user-crd.yaml, nuvolaris/apihost_util.py, nuvolaris/minio_static.py, nuvolaris/util.py, tests/k3s/whisk-user.yaml, tests/kind/whisk-user.yaml, tests/microk8s/whisk-user.yaml, tests/minio-nuv.js, tests/whisk-user.yaml
automatically assigning hostname to be assigned to new user wh…en static web bucket is deployed
=> Implement nuvolaris/nuvolaris#228

nuvolaris/apihost_util.py, nuvolaris/minio_static.py, nuvolaris/user_metadata.py, tests/microk8s/whisk-user.yaml
feature: adds STATIC_CONTENT_URL user metadata when user web bucket i…s exposed via the static ingress
=> Implements nuvolaris/nuvolaris#229

TaskfileTest.yml, nuvolaris/redis.py
fix: adding redis service port to when storing redis_url attribute for users, including nuvolaris one
=> Fix nuvolaris/nuvolaris#234

nuvolaris/ferretdb.py, nuvolaris/mongodb.py, nuvolaris/postgres_operator.py, nuvolaris/redis.py, nuvolaris/user_metadata.py, tests/k3s/whisk-user.yaml, tests/k3s/whisk.yaml
always storing redis, ferretdb, postgres metadata on user creation
=> chore: always storing redis, ferretdb, postgres metadata

clusters/eks.yml, deploy/nuvolaris-permissions/whisk-crd.yaml, deploy/redis/redis-set.yaml, nuvolaris/ferretdb.py, nuvolaris/kube.py, nuvolaris/main.py, nuvolaris/minio.py, nuvolaris/redis.py, nuvolaris/templates/01-minio-dep.yaml, nuvolaris/templates/ferretdb-sts.yaml, nuvolaris/templates/redis-conf.yaml, nuvolaris/templates/redis-set.yaml, nuvolaris/util.py, nuvolaris/version_util.py, nuvolaris/whisk_actions_deployer.py, nuvolaris/whisk_system_util.py, tests/eks/whisk.yaml, tests/k3s/whisk.yaml, tests/kind/whisk.yaml, tests/microk8s/whisk.yaml, tests/openshift/whisk.yaml
This PR provides improvement to fixe these issues
1. randomly missing nuv login system action, by improving detecting issues in execution of wsk cli response and checking for existence of whisk_system login action
2. fixes access denied error on EKS when using non root running container. on EKS a pod security context is added to specific which UID to use. This UID it is 1001 by default on all bitnami based images.
=> Fixes for nuvolaris/nuvolaris#250 and nuvolaris/nuvolaris#251

detect.sh, nuvolaris/config.py, tests/aks/whisk.yaml, tests/gke/whisk.yaml
This PR adds AKS detection to config.py
=> chore: detecting aks cluster

deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml
aligned runtimes to latest nodejs and python build
=> chore: aligned runtimes to latest nodejs and python build

.gitignore, Taskfile.yml, clusters/talos-gcp.yml, deploy/ingress-nginx/cloud-nginx-ingress.yaml
chore: simple taskfile to create a testing talos cluster on GCP
=> chore: simple taskfile to create a testing talos cluster on GCP

actions/Taskfile.yml, nuvolaris/apihost_util.py, nuvolaris/endpoint.py, tests/kind/whisk-gpt-user.yaml, tests/kind/whisk.yaml
This PR fixes an issue in /api/my ingresses pointing to the correct rewrite target that should be /api/v1/web/<namespace>
=> Fixes nuvolaris/nuvolaris-bugs#9

Dockerfile, deploy/runtimes/runtimes-preload.yaml, nuvolaris/main.py, nuvolaris/patcher.py, nuvolaris/runtimes_preloader.py, nuvolaris/runtimes_util.py, nuvolaris/templates/runtimes-job-container-attach.yaml, nuvolaris/testutil.py, nuvolaris/util.py, tests/kind/runtime_preloader_test.ipy, tests/runtimes.json
This PR adds to the operator a component to automatically configure the batch job runtime preloaded  using the default runtimes available in deployed openwhisk runtimes config map.
It also recreate the preloaded batch job in case the runtime config maps get updated.
=> Implements nuvolaris/nuvolaris#273

nuvolaris/endpoint.py
This PR deploys a new apihost-rt ingress redirecting /api/runtimes to controller root to expose runtimes info required by wskdeploy tools
=> Implements nuvolaris/nuvolaris#284

nuvolaris/endpoint.py
This fix switch ingress from /api/runtimes to /api/info to clearly expose the openwhisk controller root api URL which is returning extra information about the environment and not only the runtimes.
Currently the controller is supposed to return a JSON structure comliant with this go structure defined in the wskdeploy runtimes.go
```
type OpenWhiskInfo struct {
Support  SupportInfo          `json:"support"`
Desc     string               `json:"description"`
ApiPath  []string             `json:"api_paths"`
Runtimes map[string][]Runtime `json:"runtimes"`
Limits   Limit                `json:"limits"`
}
```
=> Fixes nuvolaris/nuvolaris#280

nuvolaris/main.py, nuvolaris/templates/generic-ingress-tpl.yaml, tests/k3s/whisk.yaml
fix: nginx-ingress annotations nginx.ingress.kubernetes.io/proxy-body-size must be set with a string value not numeric
=> Fix nuvolaris/nuvolaris-bugs#17

actions/upload/__main__.py, nuvolaris/util.py
This PR contributes a fix for upload action setting the mimetype of uploaded objects relying on python mimetypes module
=> Fix nuvolaris/nuvolaris-bugs#18

actions/Taskfile.yml, nuvolaris/minio_static.py, nuvolaris/templates/content.html, nuvolaris/templates/postgres.yaml, nuvolaris/util.py, tests/k3s/whisk-saas.yaml
This PR provides fixes the following improvements/fix
- improvements: ensure that static and kubegres uses the configured nuvolaris.storageclass parameter when allocating volume, instead of using the default storage class.
- fix: nginx static content ingress was erroneously configured resulting in returning always the bucket index.html despite the requested resource was pointing to another URL.
=> Fixes nuvolaris/nuvolaris#300

TaskfileDev.yml, actions/Taskfile.yml, nuvolaris/whisk_system_util.py
fix: using OW_CONTROLLER_HOST and OW_CONTROLLER_PORT env variable due… to a clash with k8s env variable CONTROLLER_PORT when using using nuv update operator
=> Fix nuvolaris/nuvolaris-bugs#26

actions/devel/minio/command/minio.py
This PR provides the system action implementation supporting the new command
`nuv devel minio clean`
=> Implements nuvolaris/nuvolaris#318

nuvolaris/apihost_util.py
This PR contributes a fix to properly handle the nuvolaris.protocol parameter
=> chore: fix in supporting nuvolaris.protocol parameter

deploy/nuvolaris-permissions/whisk-user-crd.yaml, nuvolaris/minio.py, nuvolaris/minio_util.py, tests/kind/whisk-user.yaml
This PR contributes a small improvements giving the possibility to limit MINIO buckets quota for a specific whisk user
=> Implements nuvolaris/nuvolaris#324

deploy/nginx-static/nginx-static-cm.yaml, nuvolaris/templates/nginx-static-cm.yaml
fix: improvements in nginx config for better supporting SPA apps host…ed under user web bucket
=> Improves SPA support under user web buckets

deploy/nginx-static/nginx-static-cm.yaml, nuvolaris/templates/nginx-static-cm.yaml
fix: spa support for nginx proxy
=> fix: spa support for nginx proxy

deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml
chore: updates to python and nodejs runtimes
=> chore: updates to python and nodejs runtimes

.gitignore, Dockerfile, TaskfileBuild.yml, run.sh, whisk-system.sh
support for volumes on deploy folder by creating a tar at build time so the deploy folder is mounted on an empty volume it is properly initialized
=> implement nuvolaris/nuvolaris#342 -

Dockerfile
chore: assigning uid and guid as 1001 to nuvolaris user
=> chore: assigning uid and guid as 1001 to nuvolaris user

nuvolaris/cronjob.py, nuvolaris/endpoint.py, nuvolaris/ferretdb.py, nuvolaris/issuer.py, nuvolaris/minio.py, nuvolaris/minio_static.py, nuvolaris/postgres_operator.py, nuvolaris/redis.py, nuvolaris/util.py
This PR fix a bug caused by wrong status key entry when applying configuration changes, that was causing an unrecoverable exception and forcing the operator to retry the the wsk/controller update operation.
=> Fix nuvolaris/nuvolaris#348

nuvolaris/apihost_util.py, nuvolaris/endpoint.py, nuvolaris/minio_static.py
feat: adds an extra www ingress for the nuvolaris web bucket and api/…my endpoints
=> Implements nuvolaris/nuvolaris#349

actions/login/__main__.py, nuvolaris/minio.py, nuvolaris/minio_ingress.py, nuvolaris/nuvolaris_metadata.py, nuvolaris/openwhisk.py, nuvolaris/user_metadata.py, nuvolaris/util.py
fix: ensure compatibility with ops s3 related tasks
=> fix: ensure compatibility with ops s3 related tasks

actions/devel/upload/__main__.py, actions/login/__main__.py, nuvolaris/endpoint.py, nuvolaris/operator_util.py, nuvolaris/whisk_actions_deployer.py
upload action was not supporting DELETE option
=> fix: upload action was not supporting DELETE option
