nuvolaris/nuvolaris-operator

deploy/mongodb/README.md
deploy/mongodb/config/manager/manager.yaml
deploy/mongodb/config/rbac/role.yaml
deploy/mongodb/config/rbac/role_binding.yaml
deploy/mongodb/config/rbac/role_binding_database.yaml
deploy/mongodb/config/rbac/role_database.yaml
deploy/mongodb/config/rbac/service_account.yaml
deploy/mongodb/config/rbac/service_account_database.yaml
deploy/mongodb/crd/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
deploy/mongodb/mongodb.com_v1_mongodbcommunity_cr.yaml

Instructions are in the README file.
I left the defaults for replicaset (3 replicas), if it's too much just modify the "members" property in deploy/mongodb/mongodb.com_v1_mongodbcommunity_cr.yaml

Minimal MongoDB deployment using the community operator

---

clusters/eks-cluster.yml
clusters/eks.yml

Changed the eke cluster setup to create a nuvolaris-eks cluster in AWS region eu-east-1. After task eke:create is completed ingress and cert-manager can be added by executing task eks:setup

chore: updated task to setup an EKS cluster under the name nuvolaris-eks

---

deploy/mongodb-standalone/mongodb-sts.yaml
nuvolaris/templates/mongodb-sts.yaml

Mongodb standalone deployer was using the latest version of mongodb 5 using mongosh  based readiness and liveness probe. it looks like mongosh suffer performance issues which ere causing continuous restart due to liveness probe failure. 
This patch uses mongodb 5.0.11 and uses mongo based probes and issues seems to be solved now. 
There are quite a lot of issues regarding mongosh performance/memory problems as for instance https://jira.mongodb.org/browse/MONGOSH-1240?jql=text%20~%20%22mongosh%22
To update nuvolaris standalone mongodb deployer it is necessary to take into account wether mongo shell it is still supported or not.

[MONGODB-STANDALONE]: FIX for probe failures causing restarting

---

deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml
nuvolaris/minio.py
nuvolaris/templates/standalone-sts.yaml
tests/api.js
tests/kind/minio_test.ipy
tests/kind/wskadmin.ipy
wskadmin.sh

Includes:
- Improvements on MINIO deployment component
- Updates runtimes.json to avoid spawing too many runtimes at startup that could be un-necessary for the standalone
- Update standalone JVM memory request to 2GB as sometimes it refuses to execute the task all actions

fix: improved minio pod readiness check and adapted corresponding test

---

nuvolaris/config.py
nuvolaris/kube.py
nuvolaris/main.py
nuvolaris/openwhisk_patcher.py
nuvolaris/openwhisk_standalone.py
tests/patcher/whisk-update.yaml

Uses kubectl rollout to perform a clean restart of OpenWhisk controller when a change to runtimes or whisk file is detected.

Improves nuvolaris/nuvolaris#146

---

Dockerfile

To give stability to MINIO setup the operator uses the mc client version as per configured MINIO server version, had to update the download URL to use the archive URL as mc builds are moved once new version is out.

fix: updated mc client download URL used for operator image

---

nuvolaris/util.py

Using redis.volume-size now to honour whisk CRD

fix: redis volume size was configured using couhcdb.volume-size from whisk.yaml

---

.gitignore
Taskfile.yml
deploy/mongodb-standalone/mongodb-svc.yaml
deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/minio.py
nuvolaris/minio_util.py
nuvolaris/mongodb.py
nuvolaris/mongodb_operator.py
nuvolaris/redis.py
nuvolaris/util.py
tests/eks/whisk.yaml
tests/generic/whisk.yaml
tests/k3s/whisk.yaml
tests/kind/minio_static_test.ipy
tests/kind/minio_test.ipy
tests/kind/minio_util_test.ipy
tests/kind/mongodb_op_test.ipy
tests/kind/whisk.yaml
tests/lks/whisk.yaml
tests/microk8s/whisk.yaml
tests/openshift/whisk.yaml
tests/whisk.yaml

This PR enables cm/config specific annotations for system user nuvolaris when corresponding components are enabled
```
minio_access_key: 
minio_port: 
minio_secret_key: 
minio_url: 
mongodb_url: 
nuvolaris_minio_data_bucket: 
nuvolaris_minio_static_bucket: 
redis_prefix:
redis_url: 
```
The corresponding whisk.yaml CRD has been updated according to this structure 
```
redis:
volume-size: 10
default:
password: xxxx
nuvolaris:
prefix: nuv      
password: xxxxxx
mongodb:
host: mongodb
volume-size: 10
admin: 
user: whisk_admin
password: xxxxxxx
nuvolaris:
user: nuvolaris
password: xxxx
exposedExternally: False
useOperator: False
minio:
volume-size: 2
admin:
user: xxxxx
password: xxxxx    
nuvolaris:
user: nuvolaris
password: xxxxxx
```

Implements nuvolaris/nuvolaris#197

---

Taskfile.yml
TaskfileTest.yml
nuvolaris/kustomize.py
nuvolaris/mongodb_standalone.py
nuvolaris/redis.py
nuvolaris/templates/mongodb-config.yaml
nuvolaris/templates/pvc-create.yaml
nuvolaris/templates/redis_manage_user_tpl.txt
nuvolaris/util.py
tests/kind/mongodb_op_test.ipy
tests/kind/mongodb_std_test.ipy
tests/kind/whisk.yaml
tests/redis.js
tests/whisk.yaml

This PR contributes
- fixes redis nuvolaris permissions 
- add tests inside the testing operator tasks to verify that nuvolaris user can ping redis and has access to his prefixed keys
- add REDIS_PREFIX as metadata for any new created users (was missing from the response of nuv login calls)
- honor MongoDB volume size configured values

Fixes for nuvolaris/nuvolaris#201, nuvolaris/nuvolaris#202

---

actions/Taskfile.yml
deploy/minio/01-minio-dep.yaml
deploy/mongodb-standalone/mongodb-sts.yaml
deploy/nuvolaris-operator/operator-pod.yaml
deploy/redis/redis-set.yaml
nuvolaris/main.py
nuvolaris/templates/couchdb-init.yaml
nuvolaris/templates/couchdb-set-tpl.yaml
nuvolaris/templates/mongodb-config.yaml
nuvolaris/templates/mongodb-sts.yaml
nuvolaris/templates/standalone-sts.yaml
nuvolaris/version_util.py

This PR contributes a utility to automatically annotate into operator cm/config config map all deployed pod image pod versions. 
Pod to be selected needs to have
```
annotations:
whisks.nuvolaris.org/annotate-version: "true" 
```
and must have a `metadata.labels.name` attributes set.
For every matching pod an annotations` {pod.metadata.labels.name}_version={pod.spec.container[0].image}` is added

Implements nuvolaris/nuvolaris#200

---

deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/config.py
nuvolaris/cronjob.py
nuvolaris/endpoint.py
nuvolaris/kopf_util.py
nuvolaris/kube.py
nuvolaris/kustomize.py
nuvolaris/main.py
nuvolaris/minio.py
nuvolaris/minio_static.py
nuvolaris/mongodb.py
nuvolaris/mongodb_operator.py
nuvolaris/mongodb_standalone.py
nuvolaris/patcher.py
nuvolaris/postgres_operator.py
nuvolaris/redis.py
tests/kind/minio_test.ipy

This PR adds these redeployments capabilities to the community operator
```
- change in spec.components.tls or spec.nuvolaris.apihost -> redeployment of OpenWhisk api endpoint (apihost)
- change in spec.configs -> redeployment of OpenWhisk controller
- change in spec.components.mongodb -> add/remove mongodb
- change in spec.components.redis -> add/remove redis
- change in spec.components.cron -> add/remove cron
- change in spec.components.minio -> add/remove minio
- change in spec.components.static -> add/remove minio static provider
- change in spec.components.postgres -> add/remove postgres
```

Implements nuvolaris/nuvolaris#213

---

nuvolaris/endpoint.py
nuvolaris/templates/generic-ingress-tpl.yaml
nuvolaris/templates/generic-openshift-route-tpl.yaml
nuvolaris/time_util.py
nuvolaris/util.py

This PR provides support to align controller router/ingress timeout to the max timeout assigned to OpenWhisk controller for running actions converting the configured values in seconds.
Openwhisk timeout can be configured using ones of these formats:
- seconds: N s, Ns, N sec, Nsec
- minutes: N m, Nm, N min, Nmin
- hour: N h, Nh, N hour, Nhour
- day: N d, Nd, N day, Nday
The value will be passed as is to OpenWhisk configuration and converted in seconds to be used four route/ingress as most of the provider supports only seconds.

Implements nuvolaris/nuvolaris#221

---

deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/couchdb.py
nuvolaris/templates/couchdb-set-tpl.yaml
nuvolaris/templates/standalone-sts.yaml
nuvolaris/user_handlers.py
nuvolaris/util.py
tests/kind/whisk.yaml

feature: added possibility to customize cpu and memory resources for couchdb and controller containers. To setup the specific values defines a whisk.yaml containing in spec.configs something like
```
configs:
controller:
javaOpts: "-Xmx2048M"
resources:
cpu-req: 1
cpu-lim: 2
mem-req: "1G"
mem-lim: "2G"
couchdb:
resources:
cpu-req: 1
cpu-lim: 2
mem-req: "512M"
mem-lim: "1G" 
```
default values for cpu req and lim are 1 and 2
default values for men req and lim are 1G and 2G.

Implements nuvolaris/nuvolaris#231

---

tests/kind/whisk.yaml

using proper string format in newly added whisk.yaml attributes

fix: using proper string format in newly added whisk.yaml attributes

---

deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/couchdb.py
nuvolaris/templates/couchdb-set-tpl.yaml
nuvolaris/templates/standalone-sts.yaml
nuvolaris/util.py
tests/kind/whisk.yaml

feature: setup couchdb and controller container resources only if cor…responding spec configuration is defined

Fix nuvolaris/nuvolaris#231

---

Dockerfile
TaskfileTest.yml
deploy/ferretdb/ferretdb-sts.yaml
deploy/ferretdb/ferretdb-svc.yaml
nuvolaris/ferretdb.py
nuvolaris/main.py
nuvolaris/patcher.py
nuvolaris/postgres_operator.py
nuvolaris/templates/ferretdb-sts.yaml
nuvolaris/templates/postgres_manage_user_tpl.sql
nuvolaris/user_handlers.py
nuvolaris/util.py
tests/kind/ferretdb_test.ipy

This PR adds ferretDB as a complete replacement of MongoDB operator/standalone deployer keeping the whisk.crd and configuration parameters as they are currently defined for mongodb.
Internally FerretDB relies on a PostgresSQL database, therefore it is necessary to have it deployed even if it is not enabled in the configuration.

Implements nuvolaris/nuvolaris#235

---

deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/apihost_util.py
nuvolaris/config.py
nuvolaris/couchdb.py
nuvolaris/endpoint.py
nuvolaris/util.py
tests/config_test.ipy
tests/eks/config_test.ipy
tests/k3s/config_test.ipy
tests/kind/config_test.ipy
tests/kind/couchdb_lib_test.ipy
tests/kind/minio_static_test.ipy
tests/kind/minio_test.ipy
tests/kind/minio_util_test.ipy
tests/kind/nuvolaris_subject_test.ipy
tests/kind/userdb_util_test.ipy
tests/kind/whisk.yaml
tests/lks/config_test.ipy
tests/microk8s/config_test.ipy
tests/volume_test.ipy

This PR adds support for these new non mandatory config parameter under whisk.crd nuvolaris key: storageclass, provisioner, ingressclass, ingresslb.
The default configuration which can be omitted from whisk.yaml it is equivalent to set
```
nuvolaris:
storageclass: auto 
provisioner: auto
ingressclass: auto
ingresslb: auto
```
for kubernetes kind this is equivalent to configure nuvolaris using
```
nuvolaris:
storageclass: standard
provisioner: rancher.io/local-path
ingressclass: nginx
ingresslb: ingress-nginx/ingress-nginx-controller
```
The parameter ingresslb, if set, must be of the form <ingress-namespace>/<ingress-nginx-controller-servicename>

Fix nuvolaris/nuvolaris#241

---

nuvolaris/minio_static.py
nuvolaris/user_handlers.py
tests/generic/whisk.yaml

This PR  adds condition status to whisk-user handlers to control deployment lifecycle. Which this improvement whisk-user deployed resources get this additional informations
```
status:
conditions:
- lastTransitionTime: "2023-07-25 22:24:03"
status: "True"
type: Initialized
- lastTransitionTime: "2023-07-25 22:24:10"
status: "True"
type: Ready
```
which are giving the possibility too control wether a whisk-user custom resources has been deployed successfully using something like
`kubectl wait --for=condition=ready --timeout=60s -n nuvolaris wsku/franztt`

Improvement: adds lifecycle information to whisk-user deployed resources

---

nuvolaris/postgres_operator.py
tests/eks/whisk.yaml
tests/k3s/whisk-demo-user.yaml

This PR contributes a fix to the kubegres deployment to verify the kubegres operator readiness which was failing under EKS and GKE clusters and therefore there was no postgres instance deployed.

fix: improved kubegres operator readiness detection 

---

nuvolaris/config.py
nuvolaris/util.py
tests/config_test.ipy
tests/kind/whisk.yaml

This adds the possibility to specify OpenWhisk standalone controller image to be used using spec.controller.image entry on whisk.yaml overriding the environment variable provided in operator image.
Expected format is
`spec.controller.image:ghcr.io/nuvolaris/openwhisk-controller:0.3.0-morpheus.22122609
`

feature: allow to specify custom controller image via spec.controller.image

---

deploy/ferretdb/ferretdb-sts.yaml
deploy/minio/01-minio-dep.yaml
deploy/redis/redis-set.yaml
nuvolaris/couchdb.py
nuvolaris/ferretdb.py
nuvolaris/kustomize.py
nuvolaris/minio.py
nuvolaris/redis.py
nuvolaris/templates/01-minio-dep.yaml
nuvolaris/templates/ferretdb-sts.yaml
nuvolaris/templates/security-dep-attach.yaml
nuvolaris/templates/security-set-attach.yaml
nuvolaris/util.py
tests/volume_test.ipy

This PR uses non root based images for MINIO, REDIS and FERRETDB. In addition when deploying on Openshift deploys the corresponding PODs with a specific securityContext
```
securityContext:
capabilities:
drop:
- ALL
seccompProfile:
type: RuntimeDefault
allowPrivilegeEscalation: false
readOnlyRootFilesystem: false
runAsNonRoot: true
```

Implements nuvolaris/nuvolaris#246 and nuvolaris/nuvolaris#247

---

deploy/minio/01-minio-dep.yaml
deploy/nginx-static/nginx-static-sts.yaml
deploy/nuvolaris-permissions/kubegres-crd.yaml
deploy/nuvolaris-permissions/nuvolaris-kubegres-roles.yaml
deploy/nuvolaris-permissions/operator-roles.yaml
nuvolaris/minio.py
nuvolaris/templates/01-minio-dep.yaml
nuvolaris/templates/nginx-static-sts.yaml
tests/openshift/whisk.yaml

This PR provides various fixes to properly deploy nuvolaris operator to open shift
- use bitnami:nginx for the minio static provider
- fix a bug preventing MINIO deployment on open shift
- moves kubegres.crd under nuvolaris-permission to be applied before operator deployment as it may fail for some open shift specific setup

chore: various fix to deploy the operator on openshift

---

Taskfile.yml
deploy/acme-openshift/acme-rbac.yaml
deploy/acme-openshift/acme-setup.yaml
nuvolaris/issuer.py
nuvolaris/main.py
nuvolaris/templates/cluster-issuer.yaml
nuvolaris/templates/generic-openshift-route-tpl.yaml
nuvolaris/util.py
nuvolaris/whisk_system_util.py
tests/openshift/whisk.yaml

This PR provides the following improvements
- add retries attempt to whisk_system action deployment to ensure system actions (login currently) are properly deployed
- add support for acme-open shift helper when configuring a route over open shift with enabled TLS

Implements nuvolaris/nuvolaris#248

---

Taskfile.yml
deploy/nginx-static/nginx-static-cm.yaml
deploy/nginx-static/nginx-static-sts.yaml
nuvolaris/minio_static.py
nuvolaris/postgres_operator.py
nuvolaris/templates/generic-openshift-route-tpl.yaml
nuvolaris/templates/nginx-static-cm.yaml
nuvolaris/templates/nginx-static-sts.yaml
tests/openshift/whisk-user.yaml
tests/openshift/whisk.yaml

This PR fixes and provides improvements to
- fix an issue with postgres deployer when executing the script to create/drop user database by creating a /tmp/.pgpass file and passing reference with an env variable
- uses niginx-unprivileged image to be compliant with open shift requirements
- creates routes for static content adding an annotation to exclude the haproxy.router.openshift.io/rewrite-target ones which was giving problem in the route created buy the openshift-acme controller for the http-01 challenge

Fixes nuvolaris/nuvolaris#249

---

nuvolaris/openwhisk.py

Using nuvolaris-testing suite on off the shelf created kubernetes cluster on not so powerfull servers it has been noted that attempt to use OpenWhisk API fails due to some un-expected authentication issue. These are due to the fact that couchdb pod deployment may take some time and therefore openwhisk controller pad could reach readiness status even before the couchdb one. Under such cicurmstances openmwhisk couchdb metadata are not yet loaded and therefore any attempt to use openwhisk miserably fail.
This PR introduces a precheck condition on OpenWhisk standalone controller deployment based on couchdb pod readiness.

chore:  checks for couchdb pod readiness before OpenWhisk controller deployment

---

actions/Taskfile.yml
actions/system.yml
actions/upload/__main__.py
deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml
nuvolaris/templates/generic-ingress-tpl.yaml
nuvolaris/templates/whisk-system-manifest-tpl.yaml
nuvolaris/whisk_actions_deployer.py
whisk-system.sh

This PR provides a new whisk-system/upload action that can be used to upload a single file into the specific user web bucket  available under the context path `/api/v1/web/whisk-system/nuv/upload`
File can be upload via CURL command similar to 
`curl -X PUT -T <local_file_path> -H "minioauth: <auth>" ${APIHOST}/api/v1/web/whisk-system/nuv/upload/<user>/<remote_file_path>`
Examples:
`curl -X PUT -T index2.html -H "minioauth: <auth>" ${APIHOST}/api/v1/web/whisk-system/nuv/upload/nuvolaris/index2.html`
will upload  the file index2.html under the `nuvolaris-web` bucket linked to the `nuvolaris` user
`curl -X PUT -T template.json -H "minioauth: <auth>" ${APIHOST}/api/v1/web/whisk-system/nuv/upload/nuvolaris/.well-known/template.json`
will upload the the file `template.json` under …

Implements nuvolaris/nuvolaris#262

---

deploy/nuvolaris-permissions/openwhisk-runtimes-cm.yaml
deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/templates/standalone-sts.yaml
nuvolaris/util.py
tests/kind/whisk-mf-demo.yaml

This PR provides a small improvements in community operator which is giving the possibility to customise the container_pool_user_memeory which is used internally by the invoker to determine whether there is enough memory or not to launch a container to execute an action. This allow a minimum degree of scalability also for the community edition.
The metaflow plugins already uses a go action and the above fixes improves also the performances of parallel metaflow steps executed via the community edition.
WE should consider whether to add to olaris the possibility to customise memory settings for the standalone controller.

Implements nuvolaris/nuvolaris#279

---

Dockerfile

This PR fix a build issue bumping to ubuntu 22.04 LTS images instead of 22.10 which is not LTS!

fix: bumping operator image to ubuntu 22.04 LTS base image

---

deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/ferretdb.py
nuvolaris/templates/standalone-sts.yaml
nuvolaris/util.py
tests/gke/whisk.yaml
tests/kind/whisk.yaml
tests/openshift/whisk.yaml

This PR contributes following feature/fixes
- introduces the configs.limits.activations.max_allowed_payload to customize OpenWhisk controller activation max apyalod allowed size in bytes
- fix an issue in ferreted deployer which was not honouring the mongodb.volume-size configuration parameter

Implements nuvolaris/nuvolaris#301

---

nuvolaris/util.py

filter the default storageclass using explicitely {.items[?(@.…metadata.annotations.storageclass\.kubernetes\.io\/is-default-class=='true')].provisioner} as json path

fixes nuvolaris/nuvolaris-bugs#19

---

nuvolaris/main.py

on operator resume annotates again the components version, to take into account scenarios where the updated components it is the operator itself

Supports nuvolaris/nuvolaris#303

---

actions/Taskfile.yml
nuvolaris/kopf_util.py
nuvolaris/templates/nginx-static-cm.yaml
tests/kind/whisk-minimal.yaml

This PR fixes the following issues
1. enabling tis to activate https endpoint was not updating static ingress, if static was enabled too
2. improves nginx static rewrite rule to handle properly GET request for subfolders inside the user web bucket requesting by default the folder/index.html file, unless the requested URL contains a . in such case it is considered a GET for a specific file.
3. It redirects 404 error from MINIO returning from MINIO for non existing resources to the internal nginx pages, to hide completely the fact that the nginx-static it is a MINIO proxy

Fixes for nuvolaris/nuvolaris-bugs#22

---

.gitignore
actions/devel/download/__main__.py
actions/devel/ferretdb/__main__.py
actions/devel/minio/__main__.py
actions/devel/psql/__main__.py
actions/devel/redis/__main__.py
actions/devel/upload/__main__.py

fix in the .gitignore to include all the __main__.py under the actions folder. Previous configuration systematically excluded the nuv devel actions codebase.

fix: update to .gitignore to include nuv devel action __main__.py

---

.gitignore
actions/Taskfile.yml
actions/common/minio_util.py
actions/devel/download/common/minio_util.py
actions/devel/ferretdb/common/minio_util.py
actions/devel/minio/common/minio_util.py
actions/devel/psql/common/minio_util.py
actions/devel/redis/common/minio_util.py
actions/devel/upload/common/minio_util.py
actions/upload/common/minio_util.py

This PR fixes an issue in the upload system action which was not able to upload .yaml or .yml file, as the python mymetype library does not recognise such type of extension, and apparently there is not yer an official RFC.
The upload action will assign application/yaml mime type which seems to be the one mostly supported by browsers.

fix: upload action assign application/yaml mimetype to .yaml and .yml

---

nuvolaris/main.py
nuvolaris/operator_util.py
nuvolaris/whisk_actions_deployer.py

This PR contributes an improvement in the operator on_resume handler.
This handler it is normally triggered by a nuv update operator command, and one of the reason to update the operator it is to redeploy an updated version of the system action or even newer system actions.

on_resume handler redeploys also system actions

---

deploy/nuvolaris-permissions/whisk-crd.yaml
nuvolaris/apihost_util.py

This PR add support for nuvolaris.protocol: auto, used by default to auto assign the apihost protocol and gives the possibility to use https even if the tis module is not enabled.

Implements nuvolaris/nuvoalris#323

---

deploy/nuvolaris-permissions/whisk-user-crd.yaml
nuvolaris/minio.py
tests/kind/whisk-user.yaml

added capability to set storage.quota to auto defaulting to unlimited storage. This is required to simplify olaris task configuration

Extra feature nuvolaris/nuvolaris#324

---

nuvolaris/endpoint.py

fix: /api/my endpoint was not created for www based hostname

fix: /api/my endpoint was not created for www based hostname

---

Taskfile.yml
deploy/nuvolaris-permissions/whisk-crd.yaml
deploy/openwhisk-standalone/standalone-sts.yaml
deploy/postgres-operator-deploy/postgres.yaml
nuvolaris/couchdb.py
nuvolaris/ferretdb.py
nuvolaris/minio.py
nuvolaris/minio_static.py
nuvolaris/openwhisk_standalone.py
nuvolaris/postgres_operator.py
nuvolaris/redis.py
nuvolaris/templates/affinity-tolerance-dep-core-attach.yaml
nuvolaris/templates/affinity-tolerance-sts-core-attach.yaml
nuvolaris/templates/affinity-tolerance-sts-invoker-attach.yaml
nuvolaris/templates/postgres.yaml
nuvolaris/templates/standalone-sts.yaml
nuvolaris/util.py
tests/k3s/whisk-mysc2.yaml
tests/k3s/whisk.yaml
tests/kind/whisk-affinity.yaml
tests/whisk.yaml

This PR contributes the support for pod segregation going the possibility to enable pod affinity and toleration for these components
- couchdb 
- postgres 
- minio 
- ferretdb 
- minio static 
- standalone controller
- redis 
Affinity and Tolerations won't be enable in the olaris setup, but this is needed as the above components are inherited in the Enterprise version.

Implements nuvolaris/nuvolaris#350

---

nuvolaris/operator_util.py
nuvolaris/redis.py
nuvolaris/templates/redis-conf.yaml

fix: recreate nuvolaris redis namespace on operator resume as redis namespace are not persisted

Fix nuvolaris/nuvolaris#355

---

Dockerfile
deploy/nuvolaris-permissions/whisk-crd.yaml
deploy/postgres-backup/postgres-backup-conf.yaml
deploy/postgres-backup/postgres-backup-sts.yaml
nuvolaris/postgres_operator.py
nuvolaris/templates/dep-attach.yaml
nuvolaris/templates/postgres-backup-sts.yaml
nuvolaris/templates/postgres.yaml
nuvolaris/util.py
tests/kind/postgres_op_test.ipy
tests/kind/whisk.yaml
tests/whisk.yaml

This PR adds to community operator the support to enable/disable kubegres failover and backup, by handling extra parameters inside the whisk.crd.
Both failover and backup are disabled by default.
```
postgres:
description: used to configure a nuvolaris shared postgres instance
type: object
properties:
volume-size:
description: postgres volume size in GB
type: integer
replicas:
description: number of total postgres replicas (1 primary, N-1 replicas). Defaulted to 2
type: integer
failover:
description: enable or disable failover management. Defaulted to false
type: boolean
backup:
description: controls postgres automatic backup using pgdump_app based script
type: object
properties:
enabled:
description: boolean flag enabling/disabling backup. Defaulted to false
type: boolean
schedule: …
```

Implements nuvolaris/projects#113

---

deploy/couchdb/couchdb-svc.yaml
nuvolaris/couchdb.py
nuvolaris/templates/couchdb-set-tpl.yaml

This PR adds  following configurations to couchdb deployment
- adds extra labels, app: nuvolaris-couchdb replicationRole: primary
- configure the couchdb and couchdb-np services to match the labels  app: nuvolaris-couchdb replicationRole: primary

Partially implements nuvolaris/projects#98

---

nuvolaris/postgres_operator.py
nuvolaris/util.py

This PR ensure that configuration of postgres related resources is executed properly locating postgres and service with replicationRole=primary

fix: ensuring postgres config locate primary related resources
